my_string = input("Какой вид спорта вы предпочитаете? Назовите 3 вида: ")
print(my_string.upper())
print(my_string.lower())
my_string = (my_string.replace(" ", ""))
print(my_string)
print(my_string[0])
print(my_string[-1])
